name = "consume create pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3dc3215554b4b7165f71f2a4bee2572cc2de0f1ff80824a27f7af5bea982c07a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
