name = "consume create pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a086815024f4e1f822dc4fa045b6df7202396b8b1c8b73603c78dfe03dc851a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
