name = "consume create pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e1af45fa947be8248754a89b1c9e50a62ffd13f14abfdeb04cf83894ef94275"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
